backend:
  name: github
  repo: SumitRajwani02/shop-sales-tracker  # <--- CHANGE this to your repo!
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "sales"
    label: "Sales"
    folder: "sales"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "Product", name: "product", widget: "string" }
      - { label: "Info", name: "info", widget: "string" }
      - { label: "Price", name: "price", widget: "number" }
      - { label: "Shop", name: "shop", widget: "string" }